CSC440-Project/Models/OccupationalGroup.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CSC440_Project.Models
{
    public class OccupationalGroup
    {
        public virtual int Id { get; set; }
        public virtual string OccupationalCode { get; set; }
        public virtual string GroupName { get; set; }
        public virtual int CurrentEmploymentNumber { get; set; }
        public virtual int FutureEmploymentNumber { get; set; }
        public virtual double PercentChange { get; set; }
        public virtual int NumberChange { get; set; }
        public virtual int Replacements { get; set; }
        public virtual int Openings { get; set; }
        public virtual int MedianAnnualWage { get; set; }
    }
}

CSC440-Project/Controllers/AdminController.cs
using CSC440_Project.Attributes;
using CSC440_Project.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CSC440_Project.Modules;
using System.IO;

namespace CSC440_Project.Controllers
{
    [UserAuthorize]
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Upload()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UploadFile(string filepath)
        {
            //we want to check here that the first file in the request is not null
            if (Request.Files[0] != null)
            {
                var file = Request.Files[0];

                //byte[] data = new byte[file.ContentLength];

                //Stream stream = new MemoryStream(data);

                ExcelParser.ProcessFile(file.InputStream);
            }

            ViewBag.Message = "Success!";

            return View("Index");
        }
    }
}

CSC440-Project/Controllers/OccupationalGroupController.cs
using CSC440_Project.Modules;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CSC440_Project.Controllers
{
    public class OccupationalGroupController : Controller
    {
        protected AppDbContext _context;

        public OccupationalGroupController()
        {
            _context = new AppDbContext();
        }

        // GET: OccupationalGroup
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details(int id)
        {
            var group = _context.OccupationalGroups.FirstOrDefault(g => g.Id == id);

            return View(group);
        }
    }
}

CSC440-Project/Views/Shared/OccupationalGroups.cshtml
@model IEnumerable<CSC440_Project.Models.OccupationalGroup>

<table class="table table-responsive table-striped table-hover">
    <thead>
        <tr>
            <th>
                Occupational Group Name
            </th>
            <th>
                Current Employment (2010)
            </th>
            <th>
                Estimated Future Employment (2020)
            </th>
            <th>
                Estimated Change
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var group in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink(group.GroupName, "Details", "OccupationalGroup", new { id = group.Id }, null)
                </td>
                <td>
                    @group.CurrentEmploymentNumber
                </td>
                <td>
                    @group.FutureEmploymentNumber
                </td>
                <td>
                    @(Math.Round(group.PercentChange * 100, 1))%
                </td>
            </tr>
        }
    </tbody>
</table>

CSC440-Project/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
@using CSC440_Project.Models
@using Microsoft.AspNet.Identity.EntityFramework

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cincinnati Job Outlook Portal</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Cincinnati Job Outlook Portal", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    @*<li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                    @{
                        var currentUserId = User.Identity.GetUserId();
                        var manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new CSC440_Project.Modules.AppDbContext()));
                        var currentUser = manager.FindById(currentUserId);

                        if (currentUser != null)
                        {
                            if (currentUser.IsAdmin)
                            {
                                <li>@Html.ActionLink("Administration", "Index", "Admin")</li>
                            }
                        }
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Cincinnati Job Outlook Portal</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>